spring:
    redis:
      host: localhost
      port: 6379
      password: 1234567
      database: 0
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      timeout: 0

#Shiro配置
zimokaka:
  shiro:
    conf:
       #domain: .zimokaka.com
       cookiePath: /
       successUrl: /index
       loginView: /login
       openToken: false
       sessionTimeout: 1800000
       algorithmName: md5
       hashIterations: 5
       #不拦截的路径
       sysanon:
           - /login
           - /regist
       #跨域配置
       allowedOrigins:
           - /**
